blueprint:
  name: Puzzle Game Controller
  description: "Voice-controlled word puzzle game for View Assist. Say 'Start puzzle game', 'Play bonus game', or 'Continue puzzle game'. During gameplay, no wake word needed - just speak your answers, or say 'reveal', 'skip', 'repeat', 'pause', or 'give up'. NOTE: Create one automation per satellite you want to play on."
  domain: automation
  author: mhos
  source_url: https://github.com/mhos/puzzle-game-ha/blob/main/homeassistant/blueprints/automation/puzzle_game_controller.yaml
  input:
    satellite:
      name: Voice Satellite
      description: "The assist satellite to use for this game instance. Create multiple automations for multiple satellites."
      selector:
        entity:
          filter:
            - domain: assist_satellite

mode: restart

trigger:
  # Game start commands
  - platform: conversation
    command:
      - "start puzzle game"
      - "[start] [a] [new] puzzle [game]"
    id: start
  - platform: conversation
    command:
      - "play bonus game"
      - "[start] [a] bonus [puzzle] [game]"
      - "bonus round"
    id: bonus
  - platform: conversation
    command:
      - "continue puzzle game"
      - "resume puzzle game"
      - "continue [the] [puzzle] game"
    id: continue

  # Game commands during play
  - platform: conversation
    command:
      - "reveal"
      - "reveal [a] letter"
      - "[show] [me] [a] hint"
    id: reveal
  - platform: conversation
    command:
      - "skip"
      - "pass"
      - "next [word]"
    id: skip
  - platform: conversation
    command:
      - "repeat"
      - "say [that] again"
      - "what's the clue"
      - "repeat [the] clue"
    id: repeat
  - platform: conversation
    command:
      - "pause"
      - "pause [the] [puzzle] game"
      - "stop [the] [puzzle] game"
      - "exit [the] [puzzle] game"
    id: pause
  - platform: conversation
    command:
      - "give up"
      - "I give up"
      - "end [the] [puzzle] game"
    id: giveup

  # Answer attempts - catch-all for game answers
  - platform: conversation
    command:
      - "{answer}"
      - "[the] [answer] [is] {answer}"
      - "[is] [it] {answer}"
    id: answer

  # Continuous listening - watch the configured satellite
  - platform: state
    entity_id: !input satellite
    from: responding
    to: idle
    id: continue_listening

variables:
  satellite_entity: !input satellite
  view_assist_device: >-
    {% if trigger.platform == 'conversation' and trigger.device_id is defined %}
      {{ view_assist_entity(trigger.device_id) }}
    {% else %}
      none
    {% endif %}

action:
  - choose:
      #############################################
      # START NEW GAME
      #############################################
      - conditions:
          - condition: trigger
            id: start
          # Only trigger if this satellite started the game
          - condition: template
            value_template: "{{ trigger.satellite_id == satellite_entity }}"
        sequence:
          - service: puzzle_game.start_game
            data:
              bonus: false
          - delay:
              seconds: 2
          - service: view_assist.navigate
            continue_on_error: true
            data:
              device: "{{ view_assist_device }}"
              path: "/puzzle-game"
              revert_timeout: 0
          - service: view_assist.set_state
            continue_on_error: true
            target:
              entity_id: "{{ view_assist_device }}"
            data:
              assist_prompt: kitt_bar
          - service: puzzle_game.set_session
            data:
              active: true
              satellite: "{{ satellite_entity }}"
          - delay:
              seconds: 1
          - service: assist_satellite.announce
            continue_on_error: true
            target:
              entity_id: "{{ satellite_entity }}"
            data:
              message: "{{ state_attr('sensor.puzzle_game', 'clue') }}. What's your answer?"
              preannounce: false

      #############################################
      # START BONUS GAME
      #############################################
      - conditions:
          - condition: trigger
            id: bonus
          - condition: template
            value_template: "{{ trigger.satellite_id == satellite_entity }}"
        sequence:
          - service: puzzle_game.start_game
            data:
              bonus: true
          - delay:
              seconds: 2
          - service: view_assist.navigate
            continue_on_error: true
            data:
              device: "{{ view_assist_device }}"
              path: "/puzzle-game"
              revert_timeout: 0
          - service: view_assist.set_state
            continue_on_error: true
            target:
              entity_id: "{{ view_assist_device }}"
            data:
              assist_prompt: kitt_bar
          - service: puzzle_game.set_session
            data:
              active: true
              satellite: "{{ satellite_entity }}"
          - delay:
              seconds: 1
          - service: assist_satellite.announce
            continue_on_error: true
            target:
              entity_id: "{{ satellite_entity }}"
            data:
              message: "{{ state_attr('sensor.puzzle_game', 'clue') }}. What's your answer?"
              preannounce: false

      #############################################
      # CONTINUE/RESUME GAME
      #############################################
      - conditions:
          - condition: trigger
            id: continue
          - condition: template
            value_template: "{{ trigger.satellite_id == satellite_entity }}"
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ state_attr('sensor.puzzle_game', 'is_active') != true }}"
                sequence:
                  - service: assist_satellite.announce
                    continue_on_error: true
                    target:
                      entity_id: "{{ satellite_entity }}"
                    data:
                      message: "No active game found. Say start puzzle game to begin a new one."
                      preannounce: false
                  - stop: "No active game"
          - service: view_assist.navigate
            continue_on_error: true
            data:
              device: "{{ view_assist_device }}"
              path: "/puzzle-game"
              revert_timeout: 0
          - service: view_assist.set_state
            continue_on_error: true
            target:
              entity_id: "{{ view_assist_device }}"
            data:
              assist_prompt: kitt_bar
          - service: puzzle_game.set_session
            data:
              active: true
              satellite: "{{ satellite_entity }}"
          - service: assist_satellite.announce
            continue_on_error: true
            target:
              entity_id: "{{ satellite_entity }}"
            data:
              message: "Welcome back! {{ state_attr('sensor.puzzle_game', 'clue') }}"
              preannounce: false

      #############################################
      # CONTINUOUS LISTENING - restart after response
      #############################################
      - conditions:
          - condition: trigger
            id: continue_listening
          - condition: template
            value_template: "{{ state_attr('sensor.puzzle_game', 'session_active') == true }}"
          - condition: template
            value_template: "{{ state_attr('sensor.puzzle_game', 'is_active') == true }}"
          - condition: template
            value_template: "{{ state_attr('sensor.puzzle_game', 'active_satellite') == satellite_entity }}"
        sequence:
          - delay:
              milliseconds: 500
          - service: assist_satellite.start_conversation
            target:
              entity_id: "{{ satellite_entity }}"
            data:
              start_message: ""
              preannounce: false

      #############################################
      # ANSWER ATTEMPT
      #############################################
      - conditions:
          - condition: trigger
            id: answer
          - condition: template
            value_template: "{{ state_attr('sensor.puzzle_game', 'session_active') == true }}"
          - condition: template
            value_template: "{{ state_attr('sensor.puzzle_game', 'active_satellite') == satellite_entity }}"
        sequence:
          - service: puzzle_game.submit_answer
            data:
              answer: "{{ trigger.slots.answer }}"
          - delay:
              seconds: 1
          - service: assist_satellite.announce
            continue_on_error: true
            target:
              entity_id: "{{ satellite_entity }}"
            data:
              message: "{{ state_attr('sensor.puzzle_game', 'last_message') | default('Try again.', true) }}"
              preannounce: false

      #############################################
      # REVEAL LETTER
      #############################################
      - conditions:
          - condition: trigger
            id: reveal
          - condition: template
            value_template: "{{ state_attr('sensor.puzzle_game', 'session_active') == true }}"
          - condition: template
            value_template: "{{ state_attr('sensor.puzzle_game', 'active_satellite') == satellite_entity }}"
        sequence:
          - service: puzzle_game.reveal_letter
          - delay:
              seconds: 1
          - service: assist_satellite.announce
            continue_on_error: true
            target:
              entity_id: "{{ satellite_entity }}"
            data:
              message: "{{ state_attr('sensor.puzzle_game', 'last_message') }}"
              preannounce: false

      #############################################
      # SKIP WORD
      #############################################
      - conditions:
          - condition: trigger
            id: skip
          - condition: template
            value_template: "{{ state_attr('sensor.puzzle_game', 'session_active') == true }}"
          - condition: template
            value_template: "{{ state_attr('sensor.puzzle_game', 'active_satellite') == satellite_entity }}"
        sequence:
          - service: puzzle_game.skip_word
          - delay:
              seconds: 1
          - service: assist_satellite.announce
            continue_on_error: true
            target:
              entity_id: "{{ satellite_entity }}"
            data:
              message: "{{ state_attr('sensor.puzzle_game', 'clue') }}"
              preannounce: false

      #############################################
      # REPEAT CLUE
      #############################################
      - conditions:
          - condition: trigger
            id: repeat
          - condition: template
            value_template: "{{ state_attr('sensor.puzzle_game', 'session_active') == true }}"
          - condition: template
            value_template: "{{ state_attr('sensor.puzzle_game', 'active_satellite') == satellite_entity }}"
        sequence:
          - service: puzzle_game.repeat_clue
          - delay:
              seconds: 1
          - service: assist_satellite.announce
            continue_on_error: true
            target:
              entity_id: "{{ satellite_entity }}"
            data:
              message: "{{ state_attr('sensor.puzzle_game', 'clue') }}"
              preannounce: false

      #############################################
      # PAUSE GAME
      #############################################
      - conditions:
          - condition: trigger
            id: pause
          - condition: template
            value_template: "{{ state_attr('sensor.puzzle_game', 'session_active') == true }}"
          - condition: template
            value_template: "{{ state_attr('sensor.puzzle_game', 'active_satellite') == satellite_entity }}"
        sequence:
          - service: puzzle_game.set_session
            data:
              active: false
          - service: assist_satellite.announce
            continue_on_error: true
            target:
              entity_id: "{{ satellite_entity }}"
            data:
              message: "Game paused. Say continue puzzle game to resume."
              preannounce: false

      #############################################
      # GIVE UP
      #############################################
      - conditions:
          - condition: trigger
            id: giveup
          - condition: template
            value_template: "{{ state_attr('sensor.puzzle_game', 'session_active') == true }}"
          - condition: template
            value_template: "{{ state_attr('sensor.puzzle_game', 'active_satellite') == satellite_entity }}"
        sequence:
          - service: puzzle_game.set_session
            data:
              active: false
          - service: puzzle_game.give_up
          - delay:
              seconds: 2
          - service: assist_satellite.announce
            continue_on_error: true
            target:
              entity_id: "{{ satellite_entity }}"
            data:
              message: "{{ state_attr('sensor.puzzle_game', 'last_message') | default('Game ended.', true) }}"
              preannounce: false
