blueprint:
  name: Puzzle Game Controller
  description: >
    Voice-activated word puzzle game for View Assist devices.

    This blueprint handles starting, continuing, and playing bonus rounds.
    The satellite device is automatically detected - no configuration needed!

    Prerequisites:
    - Install the Puzzle Game integration via HACS
    - Have View Assist set up with an assist satellite

    Voice Commands:
    - "Start puzzle game" - Begin a new game
    - "Play bonus game" - Start a bonus round
    - "Continue puzzle game" - Resume a paused game

    During gameplay (no wake word needed):
    - Say your answer directly
    - "spell" - Spell the word letter by letter
    - "reveal" - Reveal a letter hint
    - "skip" - Skip current word
    - "repeat" - Hear the clue again
    - "pause" - Pause the game
    - "give up" - End the game
  domain: automation
  author: mhos
  source_url: https://github.com/mhos/puzzle-game-ha/blob/main/homeassistant/blueprints/automation/puzzle_game_controller.yaml
  input: {}

mode: single

trigger:
  - platform: conversation
    command:
      - "start puzzle game"
      - "[start] [a] [new] puzzle [game]"
    id: start
  - platform: conversation
    command:
      - "play bonus game"
      - "[start] [a] bonus [puzzle] [game]"
      - "bonus round"
    id: bonus
  - platform: conversation
    command:
      - "continue puzzle game"
      - "resume puzzle game"
      - "continue [the] [puzzle] game"
    id: continue

variables:
  view_assist_device: "{{ view_assist_entity(trigger.device_id) }}"

action:
  - choose:
      #############################################
      # START NEW GAME
      #############################################
      - conditions:
          - condition: trigger
            id: start
        sequence:
          # Call the native service to start game
          - service: puzzle_game.start_game
            data:
              bonus: false

          # Wait for sensor to update
          - delay:
              seconds: 2

          # Show dashboard
          - service: view_assist.set_state
            target:
              entity_id: "{{ view_assist_device }}"
            data:
              data:
                url: "/local/puzzle_game/dashboard.html"
                mode: hold
              title: "Puzzle Game"
          - service: view_assist.navigate
            data:
              device: "{{ view_assist_device }}"
              path: "/view-assist/webpage"
              revert_timeout: 0

          # Set minimal assist prompt (KITT bar)
          - service: view_assist.set_state
            target:
              entity_id: "{{ view_assist_device }}"
            data:
              assist_prompt: kitt_bar

          # Announce first clue
          - delay:
              seconds: 1
          - service: assist_satellite.announce
            continue_on_error: true
            target:
              entity_id: "{{ trigger.satellite_id }}"
            data:
              message: "{{ state_attr('sensor.puzzle_game', 'clue') }}"
              preannounce: false

          # Announce instructions
          - delay:
              seconds: 1
          - service: assist_satellite.announce
            continue_on_error: true
            target:
              entity_id: "{{ trigger.satellite_id }}"
            data:
              message: "What would you like to do? You can answer, spell, reveal, skip, repeat, or pause."
              preannounce: false

          # Start active game session script
          - service: script.puzzle_game_active_session
            data:
              satellite_entity: "{{ trigger.satellite_id }}"

      #############################################
      # START BONUS GAME
      #############################################
      - conditions:
          - condition: trigger
            id: bonus
        sequence:
          # Call the native service to start bonus game
          - service: puzzle_game.start_game
            data:
              bonus: true

          # Wait for sensor to update
          - delay:
              seconds: 2

          # Show dashboard
          - service: view_assist.set_state
            target:
              entity_id: "{{ view_assist_device }}"
            data:
              data:
                url: "/local/puzzle_game/dashboard.html"
                mode: hold
              title: "Puzzle Game"
          - service: view_assist.navigate
            data:
              device: "{{ view_assist_device }}"
              path: "/view-assist/webpage"
              revert_timeout: 0

          # Set minimal assist prompt (KITT bar)
          - service: view_assist.set_state
            target:
              entity_id: "{{ view_assist_device }}"
            data:
              assist_prompt: kitt_bar

          # Announce first clue
          - delay:
              seconds: 1
          - service: assist_satellite.announce
            continue_on_error: true
            target:
              entity_id: "{{ trigger.satellite_id }}"
            data:
              message: "{{ state_attr('sensor.puzzle_game', 'clue') }}"
              preannounce: false

          # Announce instructions
          - delay:
              seconds: 1
          - service: assist_satellite.announce
            continue_on_error: true
            target:
              entity_id: "{{ trigger.satellite_id }}"
            data:
              message: "What would you like to do? You can answer, spell, reveal, skip, repeat, or pause."
              preannounce: false

          # Start active game session script
          - service: script.puzzle_game_active_session
            data:
              satellite_entity: "{{ trigger.satellite_id }}"

      #############################################
      # CONTINUE/RESUME GAME
      #############################################
      - conditions:
          - condition: trigger
            id: continue
        sequence:
          # Check if game is active
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ state_attr('sensor.puzzle_game', 'is_active') != true }}"
                sequence:
                  - service: assist_satellite.announce
                    continue_on_error: true
                    target:
                      entity_id: "{{ trigger.satellite_id }}"
                    data:
                      message: "No active game found. Say start puzzle game to begin a new one."
                      preannounce: false
                  - stop: "No active game"

          # Show dashboard
          - service: view_assist.set_state
            target:
              entity_id: "{{ view_assist_device }}"
            data:
              data:
                url: "/local/puzzle_game/dashboard.html"
                mode: hold
              title: "Puzzle Game"
          - service: view_assist.navigate
            data:
              device: "{{ view_assist_device }}"
              path: "/view-assist/webpage"
              revert_timeout: 0

          # Set minimal assist prompt (KITT bar)
          - service: view_assist.set_state
            target:
              entity_id: "{{ view_assist_device }}"
            data:
              assist_prompt: kitt_bar

          # Announce current clue
          - service: assist_satellite.announce
            continue_on_error: true
            target:
              entity_id: "{{ trigger.satellite_id }}"
            data:
              message: "Welcome back! {{ state_attr('sensor.puzzle_game', 'clue') }}"
              preannounce: false

          # Resume active game session script
          - service: script.puzzle_game_active_session
            data:
              satellite_entity: "{{ trigger.satellite_id }}"
