blueprint:
  name: Puzzle Game Controller
  description: "Voice-controlled word puzzle game for View Assist. Say 'Start puzzle game', 'Play bonus game', or 'Continue puzzle game'. During gameplay, no wake word needed - just speak your answers, or say 'spell', 'reveal', 'skip', 'repeat', 'pause', or 'give up'."
  domain: automation
  author: mhos
  source_url: https://github.com/mhos/puzzle-game-ha/blob/main/homeassistant/blueprints/automation/puzzle_game_controller.yaml
  input: {}

mode: restart

trigger:
  - platform: conversation
    command:
      - "start puzzle game"
      - "[start] [a] [new] puzzle [game]"
    id: start
  - platform: conversation
    command:
      - "play bonus game"
      - "[start] [a] bonus [puzzle] [game]"
      - "bonus round"
    id: bonus
  - platform: conversation
    command:
      - "continue puzzle game"
      - "resume puzzle game"
      - "continue [the] [puzzle] game"
    id: continue
  - platform: event
    event_type: puzzle_game_listen
    id: listen

variables:
  view_assist_device: >-
    {% if trigger.platform == 'event' %}
      {{ trigger.event.data.view_assist_device }}
    {% else %}
      {{ view_assist_entity(trigger.device_id) }}
    {% endif %}
  satellite_entity: >-
    {% if trigger.platform == 'event' %}
      {{ trigger.event.data.satellite_entity }}
    {% else %}
      {{ trigger.satellite_id }}
    {% endif %}

action:
  - choose:
      #############################################
      # START NEW GAME
      #############################################
      - conditions:
          - condition: trigger
            id: start
        sequence:
          - service: puzzle_game.start_game
            data:
              bonus: false
          - delay:
              seconds: 2
          - service: view_assist.navigate
            data:
              device: "{{ view_assist_device }}"
              path: "/puzzle-game"
              revert_timeout: 0
          - service: view_assist.set_state
            target:
              entity_id: "{{ view_assist_device }}"
            data:
              assist_prompt: kitt_bar
          - delay:
              seconds: 1
          - service: assist_satellite.announce
            continue_on_error: true
            target:
              entity_id: "{{ satellite_entity }}"
            data:
              message: "{{ state_attr('sensor.puzzle_game', 'clue') }}"
              preannounce: false
          - delay:
              seconds: 1
          - service: assist_satellite.announce
            continue_on_error: true
            target:
              entity_id: "{{ satellite_entity }}"
            data:
              message: "What would you like to do? You can answer, spell, reveal, skip, repeat, or pause."
              preannounce: false
          - service: puzzle_game.set_session
            data:
              active: true
          # Fire event to start listening
          - event: puzzle_game_listen
            event_data:
              view_assist_device: "{{ view_assist_device }}"
              satellite_entity: "{{ satellite_entity }}"

      #############################################
      # START BONUS GAME
      #############################################
      - conditions:
          - condition: trigger
            id: bonus
        sequence:
          - service: puzzle_game.start_game
            data:
              bonus: true
          - delay:
              seconds: 2
          - service: view_assist.navigate
            data:
              device: "{{ view_assist_device }}"
              path: "/puzzle-game"
              revert_timeout: 0
          - service: view_assist.set_state
            target:
              entity_id: "{{ view_assist_device }}"
            data:
              assist_prompt: kitt_bar
          - delay:
              seconds: 1
          - service: assist_satellite.announce
            continue_on_error: true
            target:
              entity_id: "{{ satellite_entity }}"
            data:
              message: "{{ state_attr('sensor.puzzle_game', 'clue') }}"
              preannounce: false
          - delay:
              seconds: 1
          - service: assist_satellite.announce
            continue_on_error: true
            target:
              entity_id: "{{ satellite_entity }}"
            data:
              message: "What would you like to do? You can answer, spell, reveal, skip, repeat, or pause."
              preannounce: false
          - service: puzzle_game.set_session
            data:
              active: true
          # Fire event to start listening
          - event: puzzle_game_listen
            event_data:
              view_assist_device: "{{ view_assist_device }}"
              satellite_entity: "{{ satellite_entity }}"

      #############################################
      # CONTINUE/RESUME GAME
      #############################################
      - conditions:
          - condition: trigger
            id: continue
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ state_attr('sensor.puzzle_game', 'is_active') != true }}"
                sequence:
                  - service: assist_satellite.announce
                    continue_on_error: true
                    target:
                      entity_id: "{{ satellite_entity }}"
                    data:
                      message: "No active game found. Say start puzzle game to begin a new one."
                      preannounce: false
                  - stop: "No active game"
          - service: view_assist.navigate
            data:
              device: "{{ view_assist_device }}"
              path: "/puzzle-game"
              revert_timeout: 0
          - service: view_assist.set_state
            target:
              entity_id: "{{ view_assist_device }}"
            data:
              assist_prompt: kitt_bar
          - service: assist_satellite.announce
            continue_on_error: true
            target:
              entity_id: "{{ satellite_entity }}"
            data:
              message: "Welcome back! {{ state_attr('sensor.puzzle_game', 'clue') }}"
              preannounce: false
          - service: puzzle_game.set_session
            data:
              active: true
          # Fire event to start listening
          - event: puzzle_game_listen
            event_data:
              view_assist_device: "{{ view_assist_device }}"
              satellite_entity: "{{ satellite_entity }}"

      #############################################
      # LISTEN FOR PLAYER INPUT (triggered by event)
      #############################################
      - conditions:
          - condition: trigger
            id: listen
        sequence:
          # Check if game is still active
          - condition: template
            value_template: "{{ state_attr('sensor.puzzle_game', 'session_active') == true and state_attr('sensor.puzzle_game', 'is_active') == true }}"

          # Small delay before listening
          - delay:
              seconds: 1

          # Ask for input
          - variables:
              player_action: null
          - action: assist_satellite.ask_question
            continue_on_error: true
            data:
              question: ""
              entity_id: "{{ satellite_entity }}"
              preannounce: false
              answers:
                - id: reveal
                  sentences:
                    - "reveal"
                    - "reveal a letter"
                    - "show me a letter"
                    - "hint"
                - id: skip
                  sentences:
                    - "skip"
                    - "pass"
                    - "next"
                    - "skip word"
                - id: repeat
                  sentences:
                    - "repeat"
                    - "say that again"
                    - "what's the clue"
                    - "repeat clue"
                - id: pause
                  sentences:
                    - "pause"
                    - "stop"
                    - "exit"
                    - "I'll be back"
                - id: giveup
                  sentences:
                    - "give up"
                    - "I give up"
                    - "end game"
                - id: spell
                  sentences:
                    - "spell"
                    - "spell it"
                    - "spell the word"
                    - "spell my answer"
                - id: answer
                  sentences:
                    - "{answer}"
                    - "the answer is {answer}"
                    - "is it {answer}"
            response_variable: player_action

          # Process the response
          - choose:
              # ANSWER
              - conditions:
                  - condition: template
                    value_template: "{{ player_action is defined and player_action.id is defined and player_action.id == 'answer' }}"
                sequence:
                  - service: puzzle_game.submit_answer
                    data:
                      answer: "{{ player_action.slots.answer }}"
                  - delay:
                      seconds: 1
                  - choose:
                      - conditions:
                          - condition: template
                            value_template: "{{ state_attr('sensor.puzzle_game', 'last_message').startswith('Correct') }}"
                        sequence:
                          - service: assist_satellite.announce
                            continue_on_error: true
                            target:
                              entity_id: "{{ satellite_entity }}"
                            data:
                              message: "{{ state_attr('sensor.puzzle_game', 'last_message') }}"
                              preannounce: false
                    default:
                      - service: assist_satellite.announce
                        continue_on_error: true
                        target:
                          entity_id: "{{ satellite_entity }}"
                        data:
                          message: "{{ state_attr('sensor.puzzle_game', 'last_message') }}"
                          preannounce: false

              # REVEAL
              - conditions:
                  - condition: template
                    value_template: "{{ player_action is defined and player_action.id is defined and player_action.id == 'reveal' }}"
                sequence:
                  - service: puzzle_game.reveal_letter
                  - delay:
                      seconds: 1
                  - service: assist_satellite.announce
                    continue_on_error: true
                    target:
                      entity_id: "{{ satellite_entity }}"
                    data:
                      message: "{{ state_attr('sensor.puzzle_game', 'last_message') }}"
                      preannounce: false

              # SKIP
              - conditions:
                  - condition: template
                    value_template: "{{ player_action is defined and player_action.id is defined and player_action.id == 'skip' }}"
                sequence:
                  - service: puzzle_game.skip_word
                  - delay:
                      seconds: 1
                  - service: assist_satellite.announce
                    continue_on_error: true
                    target:
                      entity_id: "{{ satellite_entity }}"
                    data:
                      message: "{{ state_attr('sensor.puzzle_game', 'clue') }}"
                      preannounce: false

              # REPEAT
              - conditions:
                  - condition: template
                    value_template: "{{ player_action is defined and player_action.id is defined and player_action.id == 'repeat' }}"
                sequence:
                  - service: puzzle_game.repeat_clue
                  - delay:
                      seconds: 1
                  - service: assist_satellite.announce
                    continue_on_error: true
                    target:
                      entity_id: "{{ satellite_entity }}"
                    data:
                      message: "{{ state_attr('sensor.puzzle_game', 'clue') }}"
                      preannounce: false

              # PAUSE
              - conditions:
                  - condition: template
                    value_template: "{{ player_action is defined and player_action.id is defined and player_action.id == 'pause' }}"
                sequence:
                  - service: puzzle_game.set_session
                    data:
                      active: false
                  - service: assist_satellite.announce
                    continue_on_error: true
                    target:
                      entity_id: "{{ satellite_entity }}"
                    data:
                      message: "Paused. Say continue puzzle game to resume."
                      preannounce: false
                  - stop: "Game paused"

              # GIVE UP
              - conditions:
                  - condition: template
                    value_template: "{{ player_action is defined and player_action.id is defined and player_action.id == 'giveup' }}"
                sequence:
                  - service: puzzle_game.set_session
                    data:
                      active: false
                  - service: puzzle_game.give_up
                  - delay:
                      seconds: 2
                  - service: assist_satellite.announce
                    continue_on_error: true
                    target:
                      entity_id: "{{ satellite_entity }}"
                    data:
                      message: "{{ state_attr('sensor.puzzle_game', 'last_message') | default('Game ended.', true) }}"
                      preannounce: false
                  - stop: "Game ended"

              # SPELL MODE
              - conditions:
                  - condition: template
                    value_template: "{{ player_action is defined and player_action.id is defined and player_action.id == 'spell' }}"
                sequence:
                  - service: assist_satellite.announce
                    continue_on_error: true
                    target:
                      entity_id: "{{ satellite_entity }}"
                    data:
                      message: "Spell mode is not available in this version. Please say your answer directly."
                      preannounce: false

            default:
              # No valid response or timeout - just continue listening
              - delay:
                  seconds: 1

          # If game is still active, fire event to listen again
          - condition: template
            value_template: "{{ state_attr('sensor.puzzle_game', 'session_active') == true and state_attr('sensor.puzzle_game', 'is_active') == true }}"
          - delay:
              seconds: 2
          - event: puzzle_game_listen
            event_data:
              view_assist_device: "{{ view_assist_device }}"
              satellite_entity: "{{ satellite_entity }}"
