blueprint:
  name: Puzzle Game Controller
  description: "Voice-controlled word puzzle game for View Assist. Say 'Start puzzle game', 'Play bonus game', or 'Continue puzzle game'. During gameplay, speak naturally - just say your answers, or say 'reveal', 'skip', 'repeat', 'pause', or 'give up'."
  domain: automation
  author: mhos
  source_url: https://github.com/mhos/puzzle-game-ha/blob/main/homeassistant/blueprints/automation/puzzle_game_controller.yaml
  input:
    satellite:
      name: Voice Satellite
      description: "The assist satellite to use for this game instance."
      selector:
        entity:
          filter:
            - domain: assist_satellite

mode: restart

trigger:
  # Game start commands - these are the ONLY conversation triggers
  - platform: conversation
    command:
      - "start puzzle game"
      - "[start] [a] [new] puzzle [game]"
    id: start
  - platform: conversation
    command:
      - "play bonus game"
      - "[start] [a] bonus [puzzle] [game]"
      - "bonus round"
    id: bonus
  - platform: conversation
    command:
      - "continue puzzle game"
      - "resume puzzle game"
      - "continue [the] [puzzle] game"
    id: "continue"

  # Event trigger for continuous question loop
  - platform: event
    event_type: puzzle_game_ask
    id: ask_question

variables:
  satellite_entity: !input satellite
  view_assist_device: >-
    {% if trigger.platform == 'conversation' and trigger.device_id is defined %}
      {{ view_assist_entity(trigger.device_id) }}
    {% elif trigger.platform == 'event' %}
      {{ trigger.event.data.view_assist_device | default('none') }}
    {% else %}
      none
    {% endif %}

action:
  - choose:
      #############################################
      # START NEW GAME
      #############################################
      - conditions:
          - condition: trigger
            id: start
          - condition: template
            value_template: "{{ trigger.satellite_id == satellite_entity }}"
        sequence:
          - service: puzzle_game.start_game
            data:
              bonus: false
          - delay:
              seconds: 2
          - service: view_assist.navigate
            continue_on_error: true
            data:
              device: "{{ view_assist_device }}"
              path: "/puzzle-game"
              revert_timeout: 0
          - service: view_assist.set_state
            continue_on_error: true
            target:
              entity_id: "{{ view_assist_device }}"
            data:
              assist_prompt: kitt_bar
          - service: puzzle_game.set_session
            data:
              active: true
              satellite: "{{ satellite_entity }}"
          # Fire event to start the question loop
          - event: puzzle_game_ask
            event_data:
              satellite: "{{ satellite_entity }}"
              view_assist_device: "{{ view_assist_device }}"
              first_question: true

      #############################################
      # START BONUS GAME
      #############################################
      - conditions:
          - condition: trigger
            id: bonus
          - condition: template
            value_template: "{{ trigger.satellite_id == satellite_entity }}"
        sequence:
          - service: puzzle_game.start_game
            data:
              bonus: true
          - delay:
              seconds: 2
          - service: view_assist.navigate
            continue_on_error: true
            data:
              device: "{{ view_assist_device }}"
              path: "/puzzle-game"
              revert_timeout: 0
          - service: view_assist.set_state
            continue_on_error: true
            target:
              entity_id: "{{ view_assist_device }}"
            data:
              assist_prompt: kitt_bar
          - service: puzzle_game.set_session
            data:
              active: true
              satellite: "{{ satellite_entity }}"
          # Fire event to start the question loop
          - event: puzzle_game_ask
            event_data:
              satellite: "{{ satellite_entity }}"
              view_assist_device: "{{ view_assist_device }}"
              first_question: true

      #############################################
      # CONTINUE/RESUME GAME
      #############################################
      - conditions:
          - condition: trigger
            id: "continue"
          - condition: template
            value_template: "{{ trigger.satellite_id == satellite_entity }}"
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ state_attr('sensor.puzzle_game', 'is_active') != true }}"
                sequence:
                  - service: assist_satellite.announce
                    continue_on_error: true
                    target:
                      entity_id: "{{ satellite_entity }}"
                    data:
                      message: "No active game found. Say start puzzle game to begin a new one."
                      preannounce: false
                  - stop: "No active game"
          - service: view_assist.navigate
            continue_on_error: true
            data:
              device: "{{ view_assist_device }}"
              path: "/puzzle-game"
              revert_timeout: 0
          - service: view_assist.set_state
            continue_on_error: true
            target:
              entity_id: "{{ view_assist_device }}"
            data:
              assist_prompt: kitt_bar
          - service: puzzle_game.set_session
            data:
              active: true
              satellite: "{{ satellite_entity }}"
          # Fire event to resume the question loop
          - event: puzzle_game_ask
            event_data:
              satellite: "{{ satellite_entity }}"
              view_assist_device: "{{ view_assist_device }}"
              first_question: false

      #############################################
      # ASK QUESTION LOOP (event-driven)
      #############################################
      - conditions:
          - condition: trigger
            id: ask_question
          - condition: template
            value_template: "{{ trigger.event.data.satellite == satellite_entity }}"
          - condition: template
            value_template: "{{ state_attr('sensor.puzzle_game', 'session_active') == true }}"
          - condition: template
            value_template: "{{ state_attr('sensor.puzzle_game', 'is_active') == true }}"
        sequence:
          # Announce the clue for first question or after correct answer
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ trigger.event.data.first_question == true }}"
                sequence:
                  - service: assist_satellite.announce
                    continue_on_error: true
                    target:
                      entity_id: "{{ satellite_entity }}"
                    data:
                      message: "{{ state_attr('sensor.puzzle_game', 'clue') }}"
                      preannounce: false
                  - delay:
                      seconds: 1

          # Ask for player input using ask_question
          - action: assist_satellite.ask_question
            target:
              entity_id: "{{ satellite_entity }}"
            data:
              question: "What's your answer?"
              preannounce: false
              answers:
                - id: reveal
                  sentences:
                    - "reveal"
                    - "reveal [a] letter"
                    - "hint"
                    - "show [me] [a] letter"
                - id: skip
                  sentences:
                    - "skip"
                    - "pass"
                    - "next"
                    - "next word"
                - id: repeat
                  sentences:
                    - "repeat"
                    - "say [that] again"
                    - "what's the clue"
                    - "repeat [the] clue"
                - id: pause
                  sentences:
                    - "pause"
                    - "pause [the] game"
                    - "stop"
                    - "exit"
                - id: giveup
                  sentences:
                    - "give up"
                    - "I give up"
                    - "end [the] game"
            response_variable: player_response
            continue_on_error: true

          # Check if we got a response
          - choose:
              #############################################
              # REVEAL LETTER
              #############################################
              - conditions:
                  - condition: template
                    value_template: "{{ player_response is defined and player_response.id == 'reveal' }}"
                sequence:
                  - service: puzzle_game.reveal_letter
                  - delay:
                      milliseconds: 500
                  - service: assist_satellite.announce
                    continue_on_error: true
                    target:
                      entity_id: "{{ satellite_entity }}"
                    data:
                      message: "{{ state_attr('sensor.puzzle_game', 'last_message') }}"
                      preannounce: false
                  - delay:
                      seconds: 1
                  # Continue the loop
                  - event: puzzle_game_ask
                    event_data:
                      satellite: "{{ satellite_entity }}"
                      view_assist_device: "{{ view_assist_device }}"
                      first_question: false

              #############################################
              # SKIP WORD
              #############################################
              - conditions:
                  - condition: template
                    value_template: "{{ player_response is defined and player_response.id == 'skip' }}"
                sequence:
                  - service: puzzle_game.skip_word
                  - delay:
                      milliseconds: 500
                  - service: assist_satellite.announce
                    continue_on_error: true
                    target:
                      entity_id: "{{ satellite_entity }}"
                    data:
                      message: "Skipped. {{ state_attr('sensor.puzzle_game', 'clue') }}"
                      preannounce: false
                  - delay:
                      seconds: 1
                  # Continue the loop
                  - event: puzzle_game_ask
                    event_data:
                      satellite: "{{ satellite_entity }}"
                      view_assist_device: "{{ view_assist_device }}"
                      first_question: false

              #############################################
              # REPEAT CLUE
              #############################################
              - conditions:
                  - condition: template
                    value_template: "{{ player_response is defined and player_response.id == 'repeat' }}"
                sequence:
                  - service: puzzle_game.repeat_clue
                  - delay:
                      milliseconds: 500
                  - service: assist_satellite.announce
                    continue_on_error: true
                    target:
                      entity_id: "{{ satellite_entity }}"
                    data:
                      message: "{{ state_attr('sensor.puzzle_game', 'clue') }}"
                      preannounce: false
                  - delay:
                      seconds: 1
                  # Continue the loop
                  - event: puzzle_game_ask
                    event_data:
                      satellite: "{{ satellite_entity }}"
                      view_assist_device: "{{ view_assist_device }}"
                      first_question: false

              #############################################
              # PAUSE GAME
              #############################################
              - conditions:
                  - condition: template
                    value_template: "{{ player_response is defined and player_response.id == 'pause' }}"
                sequence:
                  - service: puzzle_game.set_session
                    data:
                      active: false
                  - service: assist_satellite.announce
                    continue_on_error: true
                    target:
                      entity_id: "{{ satellite_entity }}"
                    data:
                      message: "Game paused. Say continue puzzle game to resume."
                      preannounce: false
                  - service: view_assist.set_state
                    continue_on_error: true
                    target:
                      entity_id: "{{ view_assist_device }}"
                    data:
                      assist_prompt: ""
                  # Don't continue the loop - game is paused

              #############################################
              # GIVE UP
              #############################################
              - conditions:
                  - condition: template
                    value_template: "{{ player_response is defined and player_response.id == 'giveup' }}"
                sequence:
                  - service: puzzle_game.set_session
                    data:
                      active: false
                  - service: puzzle_game.give_up
                  - delay:
                      seconds: 1
                  - service: assist_satellite.announce
                    continue_on_error: true
                    target:
                      entity_id: "{{ satellite_entity }}"
                    data:
                      message: "{{ state_attr('sensor.puzzle_game', 'last_message') | default('Game ended.', true) }}"
                      preannounce: false
                  - service: view_assist.set_state
                    continue_on_error: true
                    target:
                      entity_id: "{{ view_assist_device }}"
                    data:
                      assist_prompt: ""
                  # Don't continue the loop - game ended

              #############################################
              # ANSWER ATTEMPT (anything else said)
              #############################################
              - conditions:
                  - condition: template
                    value_template: "{{ player_response is defined and player_response.sentence is defined and player_response.sentence | length > 0 }}"
                sequence:
                  - service: puzzle_game.submit_answer
                    data:
                      answer: "{{ player_response.sentence }}"
                  - delay:
                      milliseconds: 500
                  - service: assist_satellite.announce
                    continue_on_error: true
                    target:
                      entity_id: "{{ satellite_entity }}"
                    data:
                      message: "{{ state_attr('sensor.puzzle_game', 'last_message') | default('Try again.', true) }}"
                      preannounce: false
                  - delay:
                      seconds: 1
                  # Check if game is still active before continuing
                  - choose:
                      - conditions:
                          - condition: template
                            value_template: "{{ state_attr('sensor.puzzle_game', 'is_active') == true }}"
                        sequence:
                          # Continue the loop - announce next clue if word was correct
                          - event: puzzle_game_ask
                            event_data:
                              satellite: "{{ satellite_entity }}"
                              view_assist_device: "{{ view_assist_device }}"
                              first_question: "{{ (state_attr('sensor.puzzle_game', 'last_message') | default('', true)).startswith('Correct') }}"
                    default:
                      # Game completed
                      - service: view_assist.set_state
                        continue_on_error: true
                        target:
                          entity_id: "{{ view_assist_device }}"
                        data:
                          assist_prompt: ""

            # Default - no response or timeout
            default:
              - choose:
                  # If game is still active, keep asking
                  - conditions:
                      - condition: template
                        value_template: "{{ state_attr('sensor.puzzle_game', 'session_active') == true and state_attr('sensor.puzzle_game', 'is_active') == true }}"
                    sequence:
                      - delay:
                          seconds: 1
                      - event: puzzle_game_ask
                        event_data:
                          satellite: "{{ satellite_entity }}"
                          view_assist_device: "{{ view_assist_device }}"
                          first_question: false
