blueprint:
  name: Puzzle Game Controller
  description: "Voice-controlled word puzzle game for View Assist. Say 'Start puzzle game', 'Play bonus game', or 'Continue puzzle game'. During gameplay, speak naturally - just say your answers, or say 'reveal', 'skip', 'repeat', 'spell', 'pause', or 'give up'."
  domain: automation
  author: mhos
  source_url: https://github.com/mhos/puzzle-game-ha/blob/main/homeassistant/blueprints/automation/puzzle_game_controller.yaml
  input:
    satellite:
      name: Voice Satellite
      description: "The assist satellite entity (e.g., assist_satellite.vaca_xxx). Wake button and STT sensor are derived automatically from naming convention."
      selector:
        entity:
          filter:
            - domain: assist_satellite

mode: queued
max: 5

trigger:
  # Game start commands
  - platform: conversation
    command:
      - "start puzzle game"
      - "[start] [a] [new] puzzle [game]"
    id: start
  - platform: conversation
    command:
      - "play bonus game"
      - "[start] [a] bonus [puzzle] [game]"
      - "bonus round"
    id: bonus
  - platform: conversation
    command:
      - "continue puzzle game"
      - "resume puzzle game"
      - "continue [the] [puzzle] game"
    id: "continue"

  # Custom event fired by coordinator when STT sensor changes during active session
  - platform: event
    event_type: puzzle_game_speech
    id: stt_changed

variables:
  satellite_entity: !input satellite
  view_assist_device: >-
    {% if trigger.platform == 'conversation' and trigger.device_id is defined %}
      {{ view_assist_entity(trigger.device_id) }}
    {% else %}
      {{ state_attr('sensor.puzzle_game', 'view_assist_device') | default('none') }}
    {% endif %}

action:
  - choose:
      #############################################
      # START NEW GAME
      #############################################
      - conditions:
          - condition: trigger
            id: start
          - condition: template
            value_template: "{{ trigger.satellite_id == satellite_entity }}"
        sequence:
          - service: puzzle_game.start_game
            data:
              bonus: false
          - delay:
              seconds: 2
          - service: view_assist.navigate
            continue_on_error: true
            data:
              device: "{{ view_assist_device }}"
              path: "/puzzle-game"
              revert_timeout: 0
          - service: view_assist.set_state
            continue_on_error: true
            target:
              entity_id: "{{ view_assist_device }}"
            data:
              assist_prompt: kitt_bar
          - service: puzzle_game.set_session
            data:
              active: true
              satellite: "{{ satellite_entity }}"
              view_assist_device: "{{ view_assist_device }}"
          - delay:
              seconds: 1
          # Announce the first clue
          - service: assist_satellite.announce
            continue_on_error: true
            target:
              entity_id: "{{ satellite_entity }}"
            data:
              message: "{{ state_attr('sensor.puzzle_game', 'clue') }}. What's your answer?"
              preannounce: false
          # Wait for announcement to finish, then trigger listening
          - wait_template: "{{ is_state(satellite_entity, 'idle') }}"
            timeout: "00:00:30"
          - delay:
              milliseconds: 500
          - service: assist_satellite.start_conversation
            target:
              entity_id: "{{ satellite_entity }}"
            data:
              start_message: ""
              extra_system_prompt: "You are in puzzle game mode. The user is playing a word puzzle game. Do NOT respond to their speech - just say OK or stay completely silent. The game automation will handle their answer. Do not try to help, answer questions, or have a conversation."

      #############################################
      # START BONUS GAME
      #############################################
      - conditions:
          - condition: trigger
            id: bonus
          - condition: template
            value_template: "{{ trigger.satellite_id == satellite_entity }}"
        sequence:
          - service: puzzle_game.start_game
            data:
              bonus: true
          - delay:
              seconds: 2
          - service: view_assist.navigate
            continue_on_error: true
            data:
              device: "{{ view_assist_device }}"
              path: "/puzzle-game"
              revert_timeout: 0
          - service: view_assist.set_state
            continue_on_error: true
            target:
              entity_id: "{{ view_assist_device }}"
            data:
              assist_prompt: kitt_bar
          - service: puzzle_game.set_session
            data:
              active: true
              satellite: "{{ satellite_entity }}"
              view_assist_device: "{{ view_assist_device }}"
          - delay:
              seconds: 1
          # Announce the first clue
          - service: assist_satellite.announce
            continue_on_error: true
            target:
              entity_id: "{{ satellite_entity }}"
            data:
              message: "{{ state_attr('sensor.puzzle_game', 'clue') }}. What's your answer?"
              preannounce: false
          # Wait for announcement to finish, then trigger listening
          - wait_template: "{{ is_state(satellite_entity, 'idle') }}"
            timeout: "00:00:30"
          - delay:
              milliseconds: 500
          - service: assist_satellite.start_conversation
            target:
              entity_id: "{{ satellite_entity }}"
            data:
              start_message: ""
              extra_system_prompt: "You are in puzzle game mode. The user is playing a word puzzle game. Do NOT respond to their speech - just say OK or stay completely silent. The game automation will handle their answer. Do not try to help, answer questions, or have a conversation."

      #############################################
      # CONTINUE/RESUME GAME
      #############################################
      - conditions:
          - condition: trigger
            id: "continue"
          - condition: template
            value_template: "{{ trigger.satellite_id == satellite_entity }}"
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ state_attr('sensor.puzzle_game', 'is_active') != true }}"
                sequence:
                  - service: assist_satellite.announce
                    continue_on_error: true
                    target:
                      entity_id: "{{ satellite_entity }}"
                    data:
                      message: "No active game found. Say start puzzle game to begin a new one."
                      preannounce: false
                  - stop: "No active game"
          - service: view_assist.navigate
            continue_on_error: true
            data:
              device: "{{ view_assist_device }}"
              path: "/puzzle-game"
              revert_timeout: 0
          - service: view_assist.set_state
            continue_on_error: true
            target:
              entity_id: "{{ view_assist_device }}"
            data:
              assist_prompt: kitt_bar
          - service: puzzle_game.set_session
            data:
              active: true
              satellite: "{{ satellite_entity }}"
              view_assist_device: "{{ view_assist_device }}"
          # Announce welcome back
          - service: assist_satellite.announce
            continue_on_error: true
            target:
              entity_id: "{{ satellite_entity }}"
            data:
              message: "Welcome back! {{ state_attr('sensor.puzzle_game', 'clue') }}"
              preannounce: false
          # Wait for announcement to finish, then trigger listening
          - wait_template: "{{ is_state(satellite_entity, 'idle') }}"
            timeout: "00:00:30"
          - delay:
              milliseconds: 500
          - service: assist_satellite.start_conversation
            target:
              entity_id: "{{ satellite_entity }}"
            data:
              start_message: ""
              extra_system_prompt: "You are in puzzle game mode. The user is playing a word puzzle game. Do NOT respond to their speech - just say OK or stay completely silent. The game automation will handle their answer. Do not try to help, answer questions, or have a conversation."

      #############################################
      # PROCESS SPEECH (custom event from coordinator)
      #############################################
      - conditions:
          - condition: trigger
            id: stt_changed
          # Game must be active
          - condition: template
            value_template: "{{ state_attr('sensor.puzzle_game', 'session_active') == true }}"
          - condition: template
            value_template: "{{ state_attr('sensor.puzzle_game', 'is_active') == true }}"
        sequence:
          - variables:
              # Clean up speech: lowercase, trim whitespace, remove trailing punctuation
              spoken_text: "{{ trigger.event.data.text | lower | trim | regex_replace('[.!?,]+$', '') | trim }}"

          # Ignore if this looks like a game start/continue command (already handled by conversation trigger)
          - condition: template
            value_template: "{{ 'start puzzle' not in spoken_text and 'puzzle game' not in spoken_text and 'bonus game' not in spoken_text and 'continue puzzle' not in spoken_text and 'resume puzzle' not in spoken_text }}"

          - choose:
              #############################################
              # REVEAL LETTER
              #############################################
              - conditions:
                  - condition: template
                    value_template: "{{ 'reveal' in spoken_text or 'hint' in spoken_text or spoken_text == 'letter' }}"
                sequence:
                  - service: puzzle_game.reveal_letter
                  - delay:
                      milliseconds: 500
                  - service: assist_satellite.announce
                    continue_on_error: true
                    target:
                      entity_id: "{{ satellite_entity }}"
                    data:
                      message: "{{ state_attr('sensor.puzzle_game', 'last_message') }}"
                      preannounce: false

              #############################################
              # SKIP WORD
              #############################################
              - conditions:
                  - condition: template
                    value_template: "{{ 'skip' in spoken_text or 'pass' in spoken_text or 'next' in spoken_text }}"
                sequence:
                  - service: puzzle_game.skip_word
                  - delay:
                      milliseconds: 500
                  - service: assist_satellite.announce
                    continue_on_error: true
                    target:
                      entity_id: "{{ satellite_entity }}"
                    data:
                      message: "Skipped. {{ state_attr('sensor.puzzle_game', 'clue') }}"
                      preannounce: false

              #############################################
              # REPEAT CLUE
              #############################################
              - conditions:
                  - condition: template
                    value_template: "{{ 'repeat' in spoken_text or 'clue' in spoken_text or 'say that again' in spoken_text }}"
                sequence:
                  - service: puzzle_game.repeat_clue
                  - delay:
                      milliseconds: 500
                  - service: assist_satellite.announce
                    continue_on_error: true
                    target:
                      entity_id: "{{ satellite_entity }}"
                    data:
                      message: "{{ state_attr('sensor.puzzle_game', 'clue') }}"
                      preannounce: false

              #############################################
              # SPELL WORD
              #############################################
              - conditions:
                  - condition: template
                    value_template: "{{ 'spell' in spoken_text }}"
                sequence:
                  - service: puzzle_game.spell_word
                  - delay:
                      milliseconds: 500
                  - service: assist_satellite.announce
                    continue_on_error: true
                    target:
                      entity_id: "{{ satellite_entity }}"
                    data:
                      message: "{{ state_attr('sensor.puzzle_game', 'last_message') }}"
                      preannounce: false

              #############################################
              # PAUSE GAME
              #############################################
              - conditions:
                  - condition: template
                    value_template: "{{ 'pause' in spoken_text or spoken_text in ['stop', 'exit'] }}"
                sequence:
                  - service: puzzle_game.set_session
                    data:
                      active: false
                  - service: assist_satellite.announce
                    continue_on_error: true
                    target:
                      entity_id: "{{ satellite_entity }}"
                    data:
                      message: "Game paused. Say continue puzzle game to resume."
                      preannounce: false
                  - service: view_assist.set_state
                    continue_on_error: true
                    target:
                      entity_id: "{{ view_assist_device }}"
                    data:
                      assist_prompt: ""
                  - stop: "Game paused"

              #############################################
              # GIVE UP
              #############################################
              - conditions:
                  - condition: template
                    value_template: "{{ 'give up' in spoken_text or 'end game' in spoken_text or 'end the game' in spoken_text or spoken_text == 'quit' }}"
                sequence:
                  - service: puzzle_game.set_session
                    data:
                      active: false
                  - service: puzzle_game.give_up
                  - delay:
                      seconds: 1
                  - service: assist_satellite.announce
                    continue_on_error: true
                    target:
                      entity_id: "{{ satellite_entity }}"
                    data:
                      message: "{{ state_attr('sensor.puzzle_game', 'last_message') | default('Game ended.', true) }}"
                      preannounce: false
                  - service: view_assist.set_state
                    continue_on_error: true
                    target:
                      entity_id: "{{ view_assist_device }}"
                    data:
                      assist_prompt: ""
                  - stop: "Game ended"

              #############################################
              # ANSWER ATTEMPT (anything else)
              #############################################
            default:
              - service: puzzle_game.submit_answer
                data:
                  answer: "{{ spoken_text }}"
              - delay:
                  milliseconds: 500
              - service: assist_satellite.announce
                continue_on_error: true
                target:
                  entity_id: "{{ satellite_entity }}"
                data:
                  message: "{{ state_attr('sensor.puzzle_game', 'last_message') | default('Try again.', true) }}"
                  preannounce: false

          # After processing, check if game is still active
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ state_attr('sensor.puzzle_game', 'is_active') == true and state_attr('sensor.puzzle_game', 'session_active') == true }}"
                sequence:
                  # If correct answer, announce next clue
                  - choose:
                      - conditions:
                          - condition: template
                            value_template: "{{ (state_attr('sensor.puzzle_game', 'last_message') | default('', true)).startswith('Correct') }}"
                        sequence:
                          - wait_template: "{{ is_state(satellite_entity, 'idle') }}"
                            timeout: "00:00:30"
                          - delay:
                              milliseconds: 500
                          - service: assist_satellite.announce
                            continue_on_error: true
                            target:
                              entity_id: "{{ satellite_entity }}"
                            data:
                              message: "{{ state_attr('sensor.puzzle_game', 'clue') }}"
                              preannounce: false
                  # Wait for any announcement to finish, then listen again
                  - wait_template: "{{ is_state(satellite_entity, 'idle') }}"
                    timeout: "00:00:30"
                  - delay:
                      milliseconds: 500
                  - service: assist_satellite.start_conversation
                    continue_on_error: true
                    target:
                      entity_id: "{{ satellite_entity }}"
                    data:
                      start_message: ""
                      extra_system_prompt: "You are in puzzle game mode. The user is playing a word puzzle game. Do NOT respond to their speech - just say OK or stay completely silent. The game automation will handle their answer. Do not try to help, answer questions, or have a conversation."
                  - service: system_log.write
                    data:
                      message: "Puzzle Game: Started conversation to continue listening"
                      level: info
            default:
              # Game completed
              - service: view_assist.set_state
                continue_on_error: true
                target:
                  entity_id: "{{ view_assist_device }}"
                data:
                  assist_prompt: ""
