blueprint:
  name: Puzzle Game Controller
  description: "Voice-controlled word puzzle game for View Assist. Say 'Start puzzle game', 'Play bonus game', or 'Continue puzzle game'. During gameplay, speak naturally - just say your answers, or say 'reveal', 'skip', 'repeat', 'pause', or 'give up'."
  domain: automation
  author: mhos
  source_url: https://github.com/mhos/puzzle-game-ha/blob/main/homeassistant/blueprints/automation/puzzle_game_controller.yaml
  input:
    satellite:
      name: Voice Satellite
      description: "The assist satellite entity (e.g., assist_satellite.vaca_xxx)"
      selector:
        entity:
          filter:
            - domain: assist_satellite
    wake_button:
      name: Wake Button
      description: "The button to trigger listening (e.g., button.vaca_xxx_wake)"
      selector:
        entity:
          filter:
            - domain: button
    stt_sensor:
      name: STT Sensor
      description: "The speech-to-text sensor (e.g., sensor.vaca_xxx_stt)"
      selector:
        entity:
          filter:
            - domain: sensor

mode: restart

trigger:
  # Game start commands
  - platform: conversation
    command:
      - "start puzzle game"
      - "[start] [a] [new] puzzle [game]"
    id: start
  - platform: conversation
    command:
      - "play bonus game"
      - "[start] [a] bonus [puzzle] [game]"
      - "bonus round"
    id: bonus
  - platform: conversation
    command:
      - "continue puzzle game"
      - "resume puzzle game"
      - "continue [the] [puzzle] game"
    id: "continue"

  # STT sensor changed - user spoke something
  - platform: state
    entity_id: !input stt_sensor
    id: stt_changed

variables:
  satellite_entity: !input satellite
  wake_button: !input wake_button
  stt_sensor: !input stt_sensor
  view_assist_device: >-
    {% if trigger.platform == 'conversation' and trigger.device_id is defined %}
      {{ view_assist_entity(trigger.device_id) }}
    {% else %}
      {{ state_attr('sensor.puzzle_game', 'view_assist_device') | default('none') }}
    {% endif %}

action:
  - choose:
      #############################################
      # START NEW GAME
      #############################################
      - conditions:
          - condition: trigger
            id: start
          - condition: template
            value_template: "{{ trigger.satellite_id == satellite_entity }}"
        sequence:
          - service: puzzle_game.start_game
            data:
              bonus: false
          - delay:
              seconds: 2
          - service: view_assist.navigate
            continue_on_error: true
            data:
              device: "{{ view_assist_device }}"
              path: "/puzzle-game"
              revert_timeout: 0
          - service: view_assist.set_state
            continue_on_error: true
            target:
              entity_id: "{{ view_assist_device }}"
            data:
              assist_prompt: kitt_bar
          - service: puzzle_game.set_session
            data:
              active: true
              satellite: "{{ satellite_entity }}"
          - delay:
              seconds: 1
          # Announce the first clue
          - service: assist_satellite.announce
            continue_on_error: true
            target:
              entity_id: "{{ satellite_entity }}"
            data:
              message: "{{ state_attr('sensor.puzzle_game', 'clue') }}. What's your answer?"
              preannounce: false
          # Wait for announcement to finish, then trigger listening
          - wait_template: "{{ is_state(satellite_entity, 'idle') }}"
            timeout: "00:00:30"
          - delay:
              milliseconds: 500
          - service: button.press
            target:
              entity_id: "{{ wake_button }}"

      #############################################
      # START BONUS GAME
      #############################################
      - conditions:
          - condition: trigger
            id: bonus
          - condition: template
            value_template: "{{ trigger.satellite_id == satellite_entity }}"
        sequence:
          - service: puzzle_game.start_game
            data:
              bonus: true
          - delay:
              seconds: 2
          - service: view_assist.navigate
            continue_on_error: true
            data:
              device: "{{ view_assist_device }}"
              path: "/puzzle-game"
              revert_timeout: 0
          - service: view_assist.set_state
            continue_on_error: true
            target:
              entity_id: "{{ view_assist_device }}"
            data:
              assist_prompt: kitt_bar
          - service: puzzle_game.set_session
            data:
              active: true
              satellite: "{{ satellite_entity }}"
          - delay:
              seconds: 1
          # Announce the first clue
          - service: assist_satellite.announce
            continue_on_error: true
            target:
              entity_id: "{{ satellite_entity }}"
            data:
              message: "{{ state_attr('sensor.puzzle_game', 'clue') }}. What's your answer?"
              preannounce: false
          # Wait for announcement to finish, then trigger listening
          - wait_template: "{{ is_state(satellite_entity, 'idle') }}"
            timeout: "00:00:30"
          - delay:
              milliseconds: 500
          - service: button.press
            target:
              entity_id: "{{ wake_button }}"

      #############################################
      # CONTINUE/RESUME GAME
      #############################################
      - conditions:
          - condition: trigger
            id: "continue"
          - condition: template
            value_template: "{{ trigger.satellite_id == satellite_entity }}"
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ state_attr('sensor.puzzle_game', 'is_active') != true }}"
                sequence:
                  - service: assist_satellite.announce
                    continue_on_error: true
                    target:
                      entity_id: "{{ satellite_entity }}"
                    data:
                      message: "No active game found. Say start puzzle game to begin a new one."
                      preannounce: false
                  - stop: "No active game"
          - service: view_assist.navigate
            continue_on_error: true
            data:
              device: "{{ view_assist_device }}"
              path: "/puzzle-game"
              revert_timeout: 0
          - service: view_assist.set_state
            continue_on_error: true
            target:
              entity_id: "{{ view_assist_device }}"
            data:
              assist_prompt: kitt_bar
          - service: puzzle_game.set_session
            data:
              active: true
              satellite: "{{ satellite_entity }}"
          # Announce welcome back
          - service: assist_satellite.announce
            continue_on_error: true
            target:
              entity_id: "{{ satellite_entity }}"
            data:
              message: "Welcome back! {{ state_attr('sensor.puzzle_game', 'clue') }}"
              preannounce: false
          # Wait for announcement to finish, then trigger listening
          - wait_template: "{{ is_state(satellite_entity, 'idle') }}"
            timeout: "00:00:30"
          - delay:
              milliseconds: 500
          - service: button.press
            target:
              entity_id: "{{ wake_button }}"

      #############################################
      # PROCESS SPEECH (STT sensor changed)
      #############################################
      - conditions:
          - condition: trigger
            id: stt_changed
          - condition: template
            value_template: "{{ state_attr('sensor.puzzle_game', 'session_active') == true }}"
          - condition: template
            value_template: "{{ state_attr('sensor.puzzle_game', 'is_active') == true }}"
          - condition: template
            value_template: "{{ trigger.to_state.state | length > 0 }}"
          - condition: template
            value_template: "{{ trigger.to_state.state != trigger.from_state.state }}"
        sequence:
          - variables:
              spoken_text: "{{ trigger.to_state.state | lower | trim }}"

          - choose:
              #############################################
              # REVEAL LETTER
              #############################################
              - conditions:
                  - condition: template
                    value_template: "{{ spoken_text in ['reveal', 'reveal a letter', 'hint', 'show me a letter', 'letter'] }}"
                sequence:
                  - service: puzzle_game.reveal_letter
                  - delay:
                      milliseconds: 500
                  - service: assist_satellite.announce
                    continue_on_error: true
                    target:
                      entity_id: "{{ satellite_entity }}"
                    data:
                      message: "{{ state_attr('sensor.puzzle_game', 'last_message') }}"
                      preannounce: false

              #############################################
              # SKIP WORD
              #############################################
              - conditions:
                  - condition: template
                    value_template: "{{ spoken_text in ['skip', 'pass', 'next', 'next word'] }}"
                sequence:
                  - service: puzzle_game.skip_word
                  - delay:
                      milliseconds: 500
                  - service: assist_satellite.announce
                    continue_on_error: true
                    target:
                      entity_id: "{{ satellite_entity }}"
                    data:
                      message: "Skipped. {{ state_attr('sensor.puzzle_game', 'clue') }}"
                      preannounce: false

              #############################################
              # REPEAT CLUE
              #############################################
              - conditions:
                  - condition: template
                    value_template: "{{ spoken_text in ['repeat', 'say that again', 'what is the clue', 'repeat the clue', 'clue'] }}"
                sequence:
                  - service: puzzle_game.repeat_clue
                  - delay:
                      milliseconds: 500
                  - service: assist_satellite.announce
                    continue_on_error: true
                    target:
                      entity_id: "{{ satellite_entity }}"
                    data:
                      message: "{{ state_attr('sensor.puzzle_game', 'clue') }}"
                      preannounce: false

              #############################################
              # PAUSE GAME
              #############################################
              - conditions:
                  - condition: template
                    value_template: "{{ spoken_text in ['pause', 'pause the game', 'stop', 'exit', 'stop the game'] }}"
                sequence:
                  - service: puzzle_game.set_session
                    data:
                      active: false
                  - service: assist_satellite.announce
                    continue_on_error: true
                    target:
                      entity_id: "{{ satellite_entity }}"
                    data:
                      message: "Game paused. Say continue puzzle game to resume."
                      preannounce: false
                  - service: view_assist.set_state
                    continue_on_error: true
                    target:
                      entity_id: "{{ view_assist_device }}"
                    data:
                      assist_prompt: ""
                  - stop: "Game paused"

              #############################################
              # GIVE UP
              #############################################
              - conditions:
                  - condition: template
                    value_template: "{{ spoken_text in ['give up', 'i give up', 'end the game', 'end game', 'quit'] }}"
                sequence:
                  - service: puzzle_game.set_session
                    data:
                      active: false
                  - service: puzzle_game.give_up
                  - delay:
                      seconds: 1
                  - service: assist_satellite.announce
                    continue_on_error: true
                    target:
                      entity_id: "{{ satellite_entity }}"
                    data:
                      message: "{{ state_attr('sensor.puzzle_game', 'last_message') | default('Game ended.', true) }}"
                      preannounce: false
                  - service: view_assist.set_state
                    continue_on_error: true
                    target:
                      entity_id: "{{ view_assist_device }}"
                    data:
                      assist_prompt: ""
                  - stop: "Game ended"

              #############################################
              # ANSWER ATTEMPT (anything else)
              #############################################
            default:
              - service: puzzle_game.submit_answer
                data:
                  answer: "{{ spoken_text }}"
              - delay:
                  milliseconds: 500
              - service: assist_satellite.announce
                continue_on_error: true
                target:
                  entity_id: "{{ satellite_entity }}"
                data:
                  message: "{{ state_attr('sensor.puzzle_game', 'last_message') | default('Try again.', true) }}"
                  preannounce: false

          # After processing, check if game is still active
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ state_attr('sensor.puzzle_game', 'is_active') == true and state_attr('sensor.puzzle_game', 'session_active') == true }}"
                sequence:
                  # If correct answer, announce next clue
                  - choose:
                      - conditions:
                          - condition: template
                            value_template: "{{ (state_attr('sensor.puzzle_game', 'last_message') | default('', true)).startswith('Correct') }}"
                        sequence:
                          - wait_template: "{{ is_state(satellite_entity, 'idle') }}"
                            timeout: "00:00:30"
                          - delay:
                              milliseconds: 500
                          - service: assist_satellite.announce
                            continue_on_error: true
                            target:
                              entity_id: "{{ satellite_entity }}"
                            data:
                              message: "{{ state_attr('sensor.puzzle_game', 'clue') }}"
                              preannounce: false
                  # Wait for any announcement to finish, then listen again
                  - wait_template: "{{ is_state(satellite_entity, 'idle') }}"
                    timeout: "00:00:30"
                  - delay:
                      milliseconds: 500
                  - service: button.press
                    target:
                      entity_id: "{{ wake_button }}"
            default:
              # Game completed
              - service: view_assist.set_state
                continue_on_error: true
                target:
                  entity_id: "{{ view_assist_device }}"
                data:
                  assist_prompt: ""
